In [70]:
import numpy as np

In [71]:
# 1.Arrays
# Creating an array
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [72]:
# 2.Accessing Elements
arr = np.array([1, 2, 3, 4, 5])

# Accessing an element with index 2
print(arr[2])


3


In [73]:
# 3.Mathematical Operations

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Adding two arrays
result = np.add(arr1, arr2)
print(result)

[5 7 9]


In [74]:
# 4.Multidimensional Arrays 
# Creating a two-dimensional array (matrix)
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [75]:
# 5.Matrix Operations 
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Multiplying two matrices
result = np.dot(arr1, arr2)
print(result)


[[19 22]
 [43 50]]


In [76]:
# 6.Statistical Operations 
arr = np.array([1, 2, 3, 4, 5])

# Calculating the mean of the array
mean_value = np.mean(arr)
print("Mean:", mean_value)

Mean: 3.0


In [77]:
# 7.Comparison and Masking
arr = np.array([1, 2, 3, 4, 5])

# Creating a mask for elements greater than 2
mask = arr > 2
print("Mask:", mask)

Mask: [False False  True  True  True]


In [78]:
# 8.Logical Operations 
arr1 = np.array([True, False, True])
arr2 = np.array([False, True, False])

# Performing element-wise logical AND operation
result_and = np.logical_and(arr1, arr2)
print("Logical AND:", result_and)

Logical AND: [False False False]


In [79]:
# 9.Saving and Loading Data
arr = np.array([1, 2, 3, 4, 5])

# Saving the array to a file
np.save('array.npy', arr)

# Loading the array from the file
loaded_arr = np.load('array.npy')
print("Loaded Array:", loaded_arr)

Loaded Array: [1 2 3 4 5]


In [80]:
# 10.Special Functions 
# Calculating the sine of an array
arr = np.array([0, np.pi/2, np.pi])
sin_values = np.sin(arr)
print("Sine Values:", sin_values)

Sine Values: [0.0000000e+00 1.0000000e+00 1.2246468e-16]


In [81]:
# 11.Set Operations
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([4, 5, 6, 7, 8])

# Finding the union of two arrays
union = np.union1d(arr1, arr2)
print("Union:", union)

# Finding the intersection of two arrays
intersection = np.intersect1d(arr1, arr2)
print("Intersection:", intersection)

# Finding the difference between two arrays
difference = np.setdiff1d(arr1, arr2)
print("Difference:", difference)


Union: [1 2 3 4 5 6 7 8]
Intersection: [4 5]
Difference: [1 2 3]
